import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Button } from '@mui/material';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Expert Crafting Sim | FF14</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Expert Crafting Sim</h1>
        <h2>Practice Makes Perfect</h2>
        <Link href="/sim" passHref>
          <Button>Get Started</Button>
        </Link>
      </main>
    </div>
  );
};

export default Home;
