import type { NextPage } from 'next';
import Head from 'next/head';
import { TextField } from '@mui/material';

const Sim: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Expert Crafting Sim | FF14</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Crafting Sim</h1>

        <div>
          <span>Configuration</span>

          <form>
            <span>Job Stats</span>
            <TextField label="Job" />
            <TextField label="Craftsmanship" type="number" />
            <TextField label="Control" type="number" />
            <TextField label="CP" type="number" />
          </form>

          <form>
            <span>HQ Ingredients</span>
            <TextField label="Ingradient X" type="number" />
          </form>

          <form>
            <span>Consumables</span>
            <TextField label="Food Buff" />
            <TextField label="Medicine Buff" />
            <TextField label="First FC Buff" />
            <TextField label="Seond FC Buff" />
          </form>
        </div>

        <div>
          <span>Recipe Status</span>

          <div>
            <span>Current Progress</span>
            <span>Total Progress</span>
          </div>

          <div>
            <span>Quality</span>
            <span>Total Quality</span>
          </div>

          <div>
            <span>Remaining CP</span>
            <span>Total CP</span>
          </div>
        </div>

        <div>
          <span>Toolkit Simulation</span>

          <span>Start</span>

          <span>
            All the actions divided by progression, quality, buff, repair, other
          </span>
        </div>
      </main>
    </div>
  );
};

export default Sim;
